
[package]
name = "simple"
description = "The simplest graphics library, inspired by LOVE2D"
version = "0.0.6"
repository = "https://github.com/alexandercampbell/simple"
keywords = ["simple","graphics","2D"]
authors = ["Alexander Campbell <alexanderhcampbell@gmail.com>"]
license = "Zlib"
readme = "README.md"

[lib]
name = "simple"
path = "src/lib.rs"
crate-type = ["static"]

[dependencies]
sdl2 = "*" # Surprise. It's actually an SDL2 wrapper.
sdl2-sys = "*"
libc = "*"
rand = "*"

# FIXME: the correct repository is actually github.com/xsleonard/rust-sdl2_image
#
# Using Darkspear7's fork for now because he has it updated to be compatible with the latest SDL2
# from AngryLawyer.
[dependencies.sdl2_image]
git = "https://github.com/Darkspear7/rust-sdl2_image.git"

